name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update system and install Nginx
      run: |
        ssh -o StrictHostKeyChecking=no etravel@13.80.156.135 "cd etravel && sudo apt-get update && sudo apt-get install nginx"

    - name: Enable Nginx site
      run: |
        ssh -o StrictHostKeyChecking=no etravel@13.80.156.135 "cd etravel && sudo ln -s /etc/nginx/sites-available/etravel.click && make nginx"

    - name: Test Nginx configuration
      run: |
        ssh -o StrictHostKeyChecking=no etravel@13.80.156.135 "sudo nginx -t"

    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no etravel@13.80.156.135 "sudo service nginx restart"
